'''
The program checks whether the given targetSum can be generated by the
elements of given array.
'''
def canSum(target, arr,ispos = {}):
    if target < 0: return False
    if target == 0: return True
    if target in ispos: return ispos[target]
    
    if target in arr: return True
    else:
        for val in arr:
            
            ispos[target] = canSum(target - val,arr,ispos)
        #print(ispos)
        return any(ispos.values())
    
if __name__ =="__main__":
    print(canSum(300,[7,14,100]))